/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import InternalViews.adminviews.AdminInfo;
import InternalViews.adminviews.AllCustomers;
import InternalViews.adminviews.ComercialUsers;
import InternalViews.adminviews.CpriceChange;
import InternalViews.adminviews.DomesticUsers;
import InternalViews.adminviews.DpriceChange;

/**
 *
 * @author m4rkm3n
 */
public class AdminAccount extends javax.swing.JFrame {
 
    /**
     * Creates new form AdminAccount
     */
    public AdminAccount() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        admininfo = new javax.swing.JMenu();
        adiminfo = new javax.swing.JMenuItem();
        billgen = new javax.swing.JMenu();
        all_users = new javax.swing.JMenuItem();
        com_users = new javax.swing.JMenuItem();
        dom_users = new javax.swing.JMenuItem();
        unitprice = new javax.swing.JMenu();
        domunitprice = new javax.swing.JMenuItem();
        comunitprice = new javax.swing.JMenuItem();
        genbill = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Account");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        admininfo.setText("Admin ");

        adiminfo.setText("Account Info");
        adiminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiminfoActionPerformed(evt);
            }
        });
        admininfo.add(adiminfo);

        jMenuBar1.add(admininfo);

        billgen.setText("Customers");

        all_users.setText("All Customers");
        all_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_usersActionPerformed(evt);
            }
        });
        billgen.add(all_users);

        com_users.setText("Comercial User");
        com_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_usersActionPerformed(evt);
            }
        });
        billgen.add(com_users);

        dom_users.setText("Domestic User");
        dom_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dom_usersActionPerformed(evt);
            }
        });
        billgen.add(dom_users);

        jMenuBar1.add(billgen);

        unitprice.setText("Change Unit Price");

        domunitprice.setText("Domastic Unit");
        domunitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domunitpriceActionPerformed(evt);
            }
        });
        unitprice.add(domunitprice);

        comunitprice.setText("Comercial Unit");
        comunitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunitpriceActionPerformed(evt);
            }
        });
        unitprice.add(comunitprice);

        jMenuBar1.add(unitprice);

        genbill.setText("Generate Bill");
        genbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genbillActionPerformed(evt);
            }
        });
        jMenuBar1.add(genbill);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void adiminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiminfoActionPerformed
        // TODO add your handling code here:
        
        AdminInfo ai=new AdminInfo();
        ai.setVisible(true);
        this.dp.add(ai);
    }//GEN-LAST:event_adiminfoActionPerformed

    private void all_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_usersActionPerformed
        // TODO add your handling code here:
        AllCustomers ac=new AllCustomers();
        ac.setVisible(true);
        this.dp.add(ac);
    }//GEN-LAST:event_all_usersActionPerformed

    private void com_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_usersActionPerformed
        // TODO add your handling code here:
        ComercialUsers cu=new ComercialUsers();
        cu.setVisible(true);
        this.dp.add(cu);
    }//GEN-LAST:event_com_usersActionPerformed

    private void dom_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dom_usersActionPerformed
        // TODO add your handling code here:
        DomesticUsers du=new DomesticUsers();
        du.setVisible(true);
        this.dp.add(du);
    }//GEN-LAST:event_dom_usersActionPerformed

    private void comunitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunitpriceActionPerformed
        // TODO add your handling code here:
        CpriceChange cpc=new CpriceChange();
        cpc.setVisible(true);
        this.dp.add(cpc);
    }//GEN-LAST:event_comunitpriceActionPerformed

    private void domunitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domunitpriceActionPerformed
        // TODO add your handling code here:
        DpriceChange dpc=new DpriceChange();
        dpc.setVisible(true);
        this.dp.add(dpc);
    }//GEN-LAST:event_domunitpriceActionPerformed

    private void genbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genbillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adiminfo;
    private javax.swing.JMenu admininfo;
    private javax.swing.JMenuItem all_users;
    private javax.swing.JMenu billgen;
    private javax.swing.JMenuItem com_users;
    private javax.swing.JMenuItem comunitprice;
    private javax.swing.JMenuItem dom_users;
    private javax.swing.JMenuItem domunitprice;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenu genbill;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu unitprice;
    // End of variables declaration//GEN-END:variables
}
