/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalViews.adminviews;

import Database.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author m4rkm3n
 */
public class AdminInfo extends javax.swing.JInternalFrame {
    Database db;
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form NewJInternalFrame
     */
    public AdminInfo() {
        initComponents();
        db = new Database();
        con = db.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        changepass = new javax.swing.JButton();
        apemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        apname = new javax.swing.JTextField();
        cpassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        save = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Admin Info");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(58, 56, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 293, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 293, -1));

        changepass.setBackground(new java.awt.Color(58, 56, 77));
        changepass.setForeground(new java.awt.Color(255, 255, 255));
        changepass.setText("Change Password");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });
        jPanel2.add(changepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, 34));

        apemail.setBackground(new java.awt.Color(58, 56, 77));
        apemail.setForeground(new java.awt.Color(255, 255, 255));
        apemail.setBorder(null);
        apemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apemailActionPerformed(evt);
            }
        });
        jPanel2.add(apemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 293, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 138, 27));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 138, 27));

        apname.setBackground(new java.awt.Color(58, 56, 77));
        apname.setForeground(new java.awt.Color(255, 255, 255));
        apname.setBorder(null);
        apname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apnameActionPerformed(evt);
            }
        });
        jPanel2.add(apname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 293, 33));

        cpassword.setBackground(new java.awt.Color(58, 56, 77));
        cpassword.setForeground(new java.awt.Color(255, 255, 255));
        cpassword.setBorder(null);
        jPanel2.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 239, 293, 33));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, 138, 27));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, 293, -1));

        save.setBackground(new java.awt.Color(58, 56, 77));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 125, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        // TODO add your handling code here:
        String sql ="";
        int res = 0;
        
        try {
            sql = "UPDATE admin SET apassword = md5(?) WHERE adminID=1";
            pst = con.prepareStatement(sql);
            if(cpassword.getPassword().length!=0){
            pst.setString(1, new String(cpassword.getPassword()));
            res = pst.executeUpdate();
            }
            if(res > 0 ){
            JOptionPane.showMessageDialog(null,"Password Changed SuccessFully.");
           
             }else {
            JOptionPane.showMessageDialog(null,"No New Password Entered");
                }
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
          
        
        
    }//GEN-LAST:event_changepassActionPerformed

    private void apemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apemailActionPerformed

    private void apnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apnameActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        String sql = "";
        ResultSet rs = null;
        try {
            sql = "SELECT * FROM admin";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();   
            while(rs.next()){
                this.apname.setText(rs.getString("aname"));
                this.apemail.setText(""+rs.getString("aemail"));

            }
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String sql ="";
        int res = 0;
        
        try {
            sql = "UPDATE admin SET aname = ?, aemail = ? WHERE adminID=1";
            pst = con.prepareStatement(sql);
            pst.setString(1, apname.getText());
            pst.setString(2, apemail.getText());
            res = pst.executeUpdate();
            if(res > 0 ){
            JOptionPane.showMessageDialog(null,"SuccessFully Saved.");
           
             }else {
            JOptionPane.showMessageDialog(null,"Some Error Occured");
                }
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField apemail;
    protected javax.swing.JTextField apname;
    private javax.swing.JButton changepass;
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
